compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-npm-audit-fix.cjs
    spec: "https://raw.githubusercontent.com/sargunv/yarn-plugin-npm-audit-fix/yarn-v3/bundles/%40yarnpkg/plugin-npm-audit-fix.js"

yarnPath: .yarn/releases/yarn-4.0.0-rc.51.cjs
